import os
import json
from groq import Groq
import dotenv
dotenv.load_dotenv()  # Charge les variables d'environnement depuis un fichier .env
class AgentSemantic:
    def __init__(self):
        # Récupération automatique de la clé API depuis les variables d'environnement
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            raise ValueError("❌ Clé API manquante ! Pense à exécuter : $env:GROQ_API_KEY='ta_cle'")
        
        self.client = Groq(api_key=api_key)
        # On utilise le modèle 70B pour une meilleure précision sémantique
        self.model = "llama-3.3-70b-versatile" 

    def _build_prompt(self, pair):
        """Prompt engineering avec Few-Shot et Chain-of-Thought."""
        ent_a = pair["entity_a"]
        ent_b = pair["entity_b"]
        ent_type = "Classe" if pair["type"] == "class" else "Propriété"

        prompt = f"""Tu es un agent expert en Web Sémantique et alignement d'ontologies (Ontology Matching).
Ton rôle est de déterminer si les deux entités suivantes (de type {ent_type}) sont sémantiquement équivalentes.

--- REGLES D'OR DE L'ALIGNEMENT (STRICT) ---
1. INTERDICTION DE CONFONDRE CONTENU ET CONTENEUR : Un article de presse (NewsArticle/NewsItem) ne peut JAMAIS être équivalent à une organisation ou une agence (Organization/Agency). Ce sont des concepts disjoints.
2. PROXIMITÉ TEMPORELLE ADMISE : Dans les flux de médias, la date de mise en ligne ('datePublished') et la date de génération du contenu ('dateCreated') partagent le même rôle de pivot temporel. Leur alignement est VALIDE.
3. Si les deux entités appartiennent à des catégories conceptuelles différentes (ex: un document écrit vs une structure morale/entreprise), tu DOIS répondre 'false'.
# Ajoutez cette règle claire dans votre prompt :
4. ÉQUIVALENCE DES ENTIÈRÉS MORALES : Les concepts représentant des structures collectives, des entreprises ou des institutions comme 'schema:Organization' et 'bbc:Agency' ou 'bbc:NewsAgency' sont sémantiquement équivalents dans ce contexte de domaine.
--- CONTEXTE À ANALYSER ---
--- ENTITÉ A ---
URI : {ent_a['uri']}
Label : {ent_a['label']}
Description : {ent_a['comment']}

--- ENTITÉ B ---
URI : {ent_b['uri']}
Label : {ent_b['label']}
Description : {ent_b['comment']}

--- CONSIGNES DE RÉPONSES ---
Rédige ton raisonnement étape par étape dans 'thought_process' en vérifiant d'abord qu'il ne s'agit pas d'une fausse équivalence (comme confondre un article avec l'agence qui l'a écrit).

Réponds au format JSON strict suivant :
{{
    "thought_process": "Ton analyse sur la nature des deux concepts.",
    "equivalent": true ou false (booléen),
    "confidence": un score entre 0.0 et 1.0 (flottant),
    "reason": "Synthèse en français."
}}"""
        return prompt

    def evaluate_pair(self, pair):
        """Soumet la paire au LLM et récupère la décision structurée."""
        prompt = self._build_prompt(pair)
        
        try:
            # Appel à l'API Groq avec activation du mode JSON
            response = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": "You are a precise data alignment assistant. You output strictly JSON."},
                    {"role": "user", "content": prompt}
                ],
                model=self.model,
                response_format={"type": "json_object"},
                temperature=0.1 # Basse température pour éviter l'aléatoire
            )
            
            # Extraction et parsing du résultat JSON
            result_json = json.loads(response.choices[0].message.content)
            
            # On injecte les URIs pour garder la traçabilité
            result_json["uri_a"] = pair["entity_a"]["uri"]
            result_json["uri_b"] = pair["entity_b"]["uri"]
            result_json["type"] = pair["type"]
            
            return result_json
            
        except Exception as e:
            print(f"❌ Erreur lors de l'analyse de la paire {pair['entity_a']['label']} / {pair['entity_b']['label']} : {e}")
            return None

# Test unitaire de l'Agent Sémantique
if __name__ == "__main__":
    # Paire de test (similaire à celle générée par l'Agent Analyste)
    paire_test = {
        'type': 'class', 
        'entity_a': {'uri': 'https://schema.org/NewsArticle', 'label': 'NewsArticle', 'comment': 'A news article, such as a piece in a newspaper or magazine.'}, 
        'entity_b': {'uri': 'http://www.bbc.co.uk/ontologies/news/NewsItem', 'label': 'NewsItem', 'comment': 'A single distinct piece of news content generated by journalists for platforms.'}
    }
    
    print("🤖 [Agent Sémantique] Analyse de la paire de test en cours...")
    agent = AgentSemantic()
    decision = agent.evaluate_pair(paire_test)
    print("\n🎯 Décision de l'IA :")
    print(json.dumps(decision, indent=4, ensure_ascii=False))